POSITIVE_LAS_DIR = "data/POSITIVE.las"
NEGATIVE_LAS_DIR = "data/NEGATIVE.las"
COMBINED_LAS_DIR = "data/COMBINED.las"

POSITIVE_GEOTIFF_DIR = "data/POSITIVE.tif"
NEGATIVE_GEOTIFF_DIR = "data/NEGATIVE.tif"
COMBINED_GEOTIFF_DIR = "data/COMBINED.tif"

KEEP_DIMS = ["x", "y", "z", "intensity"]