POSITIVE_LAS_DIR = "data/POSITIVE.las"
NEGATIVE_LAS_DIR = "data/NEGATIVE.las"
COMBINED_LAS_DIR = "data/COMBINED.las"

POSITIVE_GEOTIFF_DIR = "data/POSITIVE_STANDARDISED.tif"
NEGATIVE_GEOTIFF_DIR = "data/NEGATIVE_STANDARDISED.tif"
COMBINED_GEOTIFF_DIR = "data/COMBINED_STANDARDISED.tif"

POSITIVE_GEOTIFF_DIR_TEST = "data/POSITIVE_TEST_STANDARDISED.tif"
NEGATIVE_GEOTIFF_DIR_TEST = "data/NEGATIVE_TEST_STANDARDISED.tif"
COMBINED_GEOTIFF_DIR_TEST = "data/COMBINED_TEST_STANDARDISED.tif"

DATA_LOCATION = "data"
POSITIVE_TIFF_NAME = "POSITIVE_STANDARDISED.tif"
COMBINED_TIFF_NAME = "COMBINED_STANDARDISED.tif"

KEEP_DIMS = ["x", "y", "z", "intensity"]